apiVersion: v1
kind: Pod
metadata:
  name: ldapsearch
spec:
  containers:
  - name: ldapsearch
    image: emeraldsquad/ldapsearch
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: "1"
        memory: "1Gi"
      limits:
        cpu: "2"
        memory: "2Gi"
  restartPolicy: Always

